export const SOUS_COLLECTIONS_VIEW_STYLES = {
  root: "min-h-screen bg-base-200/40",
  pageTitle: "text-2xl font-bold tracking-tight text-base-content",
  grid: "grid gap-4 lg:grid-cols-[minmax(14rem,18rem)_1fr] xl:grid-cols-[minmax(14rem,18rem)_minmax(0,1fr)_minmax(0,1fr)]",
  subGrid: "grid gap-4 lg:col-span-1 xl:col-span-2 xl:grid-cols-2",
  panel: "rounded-2xl border border-base-content/10 bg-base-100/90 p-4 shadow-sm shadow-flow/5",
  panelTitle: "mb-3 text-sm font-semibold text-base-content",
  listBtn: "btn btn-ghost btn-sm w-full justify-start rounded-xl",
  listBtnActive: "btn btn-primary btn-sm w-full justify-start rounded-xl",
  searchInput: "input input-bordered input-sm mb-3 w-full rounded-xl border-base-content/15 bg-base-100",
  dropZone: "min-h-48 rounded-xl border-2 border-dashed border-base-content/20 bg-base-200/30 p-3 transition-colors",
  dropZoneActive: "min-h-48 rounded-xl border-2 border-dashed border-learn/50 bg-learn/10 p-3 transition-colors",
  questionRow: "mb-2 flex cursor-grab items-start gap-2 rounded-xl border border-base-content/10 bg-base-100 px-3 py-2 text-sm active:cursor-grabbing",
  badge: "badge badge-sm shrink-0",
} as const;
